jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run app
      run: python app.py
      env:
        OPENAI_KEY: ${{ secrets.OPENAI_KEY }}